### ISSUE TITLE
Remove initialization of bloc before the build function

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [lesnitsky/bloc_auth_tdd#2]
I believe the docs say that the bloc should be created within the build function rather than before

**Comment by lesnitsky** [comment]
https://bloclibrary.dev/#/testing
This example shows the same approach I've used
Can you provide me with link which has "bloc should be created within the build function rather than before"?

**Comment by ThinkDigitalSoftware** [comment]
Oh, interesting. I like the approach too, but it says it In the docs on pub.dev
Under "Unit Test a Real Bloc with blocTest"

**Comment by lesnitsky** [comment]
`setUp` is being invoked before each test, so each test is using a new instance of bloc anyways
